// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMZRBEsPSBsTFjRldPxIePsk2h_KMdK1k',
    appId: '1:619352328087:web:52b5932aeaff7275cb26d2',
    messagingSenderId: '619352328087',
    projectId: 'e-commerce-3f257',
    authDomain: 'e-commerce-3f257.firebaseapp.com',
    storageBucket: 'e-commerce-3f257.firebasestorage.app',
    measurementId: 'G-C4VTG5BKE2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFWVEvUEWjYMyFl8gHBx8k6bkes9hW7DI',
    appId: '1:619352328087:android:3147c603bccade50cb26d2',
    messagingSenderId: '619352328087',
    projectId: 'e-commerce-3f257',
    storageBucket: 'e-commerce-3f257.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI-9nEb7DeCF9JfM_qfApQMLHgEhFq3-8',
    appId: '1:619352328087:ios:c5233b52b7841223cb26d2',
    messagingSenderId: '619352328087',
    projectId: 'e-commerce-3f257',
    storageBucket: 'e-commerce-3f257.firebasestorage.app',
    androidClientId: '619352328087-nfb01kl3cfaui9cv00k89259b0j8d1cf.apps.googleusercontent.com',
    iosClientId: '619352328087-i4r5ndthbt0apjca6m41iulcsqvheqn4.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommercedash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI-9nEb7DeCF9JfM_qfApQMLHgEhFq3-8',
    appId: '1:619352328087:ios:c5233b52b7841223cb26d2',
    messagingSenderId: '619352328087',
    projectId: 'e-commerce-3f257',
    storageBucket: 'e-commerce-3f257.firebasestorage.app',
    androidClientId: '619352328087-nfb01kl3cfaui9cv00k89259b0j8d1cf.apps.googleusercontent.com',
    iosClientId: '619352328087-i4r5ndthbt0apjca6m41iulcsqvheqn4.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommercedash',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMZRBEsPSBsTFjRldPxIePsk2h_KMdK1k',
    appId: '1:619352328087:web:93647fbd013710b5cb26d2',
    messagingSenderId: '619352328087',
    projectId: 'e-commerce-3f257',
    authDomain: 'e-commerce-3f257.firebaseapp.com',
    storageBucket: 'e-commerce-3f257.firebasestorage.app',
    measurementId: 'G-86CZ8JJL1B',
  );
}
